"""
VALORANT Scouting Report Generator - Chat Interface
Cloud9 Hackathon - January 2026

A chat-based interface for coaches to get scouting reports
and ask detailed questions about opponent teams.

HOW IT WORKS:
=============
1. User selects a team to scout
2. ScoutingEngine extracts RAW DATA from DuckDB (ground truth)
3. Raw JSON data is sent to Gemini for analysis
4. Gemini generates insights GROUNDED in the actual data
5. Coach can ask follow-up questions in chat

PREVENTING HALLUCINATIONS:
==========================
- All data comes from the database (not made up by LLM)
- LLM is instructed to ONLY use provided data
- Raw data is shown alongside AI analysis
- Stats are extracted by SQL, not generated by LLM
"""

import streamlit as st
import pandas as pd
import os
from datetime import datetime
from dotenv import load_dotenv

from dynamic_scouting_engine import DynamicScoutingEngine, ScoutingEngine
from gemini_analyzer import GeminiAnalyzer, ConversationManager

# ============== CONFIGURATION ==============
# Load API key from .env file
load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Page config
st.set_page_config(
    page_title="C9 Scouting Tool",
    page_icon="🎮",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for beautiful interface
st.markdown("""
<style>
    /* Import Google Fonts */
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    /* Global Styles */
    .stApp {
        font-family: 'Inter', sans-serif;
    }
    
    /* Hide default Streamlit branding */
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    
    /* Main Header */
    .main-header {
        font-size: 2.5rem;
        font-weight: 700;
        background: linear-gradient(135deg, #ff4655 0%, #ff6b6b 50%, #ffa500 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
        margin-bottom: 0.5rem;
        text-shadow: 0 0 30px rgba(255, 70, 85, 0.3);
    }
    
    /* Sidebar Styling */
    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #0f0f23 0%, #1a1a2e 100%);
        border-right: 1px solid rgba(255, 70, 85, 0.2);
    }
    
    [data-testid="stSidebar"] .stMarkdown h2 {
        color: #ff4655 !important;
        font-weight: 600;
    }
    
    [data-testid="stSidebar"] .stMarkdown h3 {
        color: #e0e0e0 !important;
        font-size: 1rem;
        font-weight: 500;
    }
    
    /* Button Styling */
    .stButton > button {
        width: 100%;
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        border: 1px solid rgba(255, 70, 85, 0.3);
        border-radius: 10px;
        color: white;
        font-weight: 500;
        padding: 0.6rem 1rem;
        transition: all 0.3s ease;
    }
    
    .stButton > button:hover {
        border-color: #ff4655;
        box-shadow: 0 0 20px rgba(255, 70, 85, 0.3);
        transform: translateY(-2px);
    }
    
    .stButton > button[kind="primary"] {
        background: linear-gradient(135deg, #ff4655 0%, #ff6b6b 100%);
        border: none;
    }
    
    .stButton > button[kind="primary"]:hover {
        box-shadow: 0 0 25px rgba(255, 70, 85, 0.5);
    }
    
    /* Metric Cards */
    [data-testid="stMetric"] {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        border: 1px solid rgba(255, 70, 85, 0.2);
        border-radius: 12px;
        padding: 1rem;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3);
    }
    
    [data-testid="stMetric"] label {
        color: #888 !important;
        font-size: 0.85rem;
    }
    
    [data-testid="stMetric"] [data-testid="stMetricValue"] {
        color: #ff4655 !important;
        font-weight: 700;
    }
    
    /* Tab Styling */
    .stTabs [data-baseweb="tab-list"] {
        gap: 8px;
        background: transparent;
    }
    
    .stTabs [data-baseweb="tab"] {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        border-radius: 10px;
        border: 1px solid rgba(255, 70, 85, 0.2);
        color: white;
        padding: 10px 24px;
        font-weight: 500;
    }
    
    .stTabs [data-baseweb="tab"]:hover {
        border-color: #ff4655;
    }
    
    .stTabs [aria-selected="true"] {
        background: linear-gradient(135deg, #ff4655 0%, #ff6b6b 100%) !important;
        border-color: #ff4655 !important;
    }
    
    /* Chat Messages */
    [data-testid="stChatMessage"] {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        border-radius: 12px;
        border: 1px solid rgba(255, 255, 255, 0.1);
        padding: 1rem;
        margin-bottom: 1rem;
    }
    
    /* Chat Input */
    [data-testid="stChatInput"] {
        border-color: rgba(255, 70, 85, 0.3) !important;
    }
    
    [data-testid="stChatInput"]:focus-within {
        border-color: #ff4655 !important;
        box-shadow: 0 0 15px rgba(255, 70, 85, 0.2);
    }
    
    /* DataFrames */
    .stDataFrame {
        border-radius: 10px;
        overflow: hidden;
    }
    
    /* Success/Error/Info boxes */
    .stSuccess {
        background: linear-gradient(135deg, rgba(40, 167, 69, 0.2) 0%, rgba(40, 167, 69, 0.1) 100%);
        border-left: 4px solid #28a745;
        border-radius: 8px;
    }
    
    .stError {
        background: linear-gradient(135deg, rgba(255, 70, 85, 0.2) 0%, rgba(255, 70, 85, 0.1) 100%);
        border-left: 4px solid #ff4655;
        border-radius: 8px;
    }
    
    .stInfo {
        background: linear-gradient(135deg, rgba(0, 123, 255, 0.2) 0%, rgba(0, 123, 255, 0.1) 100%);
        border-left: 4px solid #007bff;
        border-radius: 8px;
    }
    
    /* Expander */
    .streamlit-expanderHeader {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        border-radius: 10px;
        border: 1px solid rgba(255, 70, 85, 0.2);
    }
    
    /* Selectbox */
    [data-testid="stSelectbox"] > div > div {
        background: #1a1a2e;
        border-color: rgba(255, 70, 85, 0.3);
        border-radius: 8px;
    }
    
    /* Slider */
    .stSlider > div > div > div {
        background: #ff4655 !important;
    }
    
    /* Stats Card */
    .stats-card {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
        border: 1px solid rgba(255, 70, 85, 0.2);
        border-radius: 12px;
        padding: 1.5rem;
        margin-bottom: 1rem;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.3);
    }
    
    .stats-card h4 {
        color: #ff4655;
        margin-bottom: 1rem;
        font-weight: 600;
    }
    
    /* Weakness badges */
    .weakness-high {
        background: linear-gradient(135deg, rgba(255, 70, 85, 0.3) 0%, rgba(255, 70, 85, 0.1) 100%);
        border-left: 4px solid #ff4655;
        padding: 0.75rem 1rem;
        border-radius: 8px;
        margin-bottom: 0.5rem;
    }
    
    .weakness-medium {
        background: linear-gradient(135deg, rgba(255, 193, 7, 0.3) 0%, rgba(255, 193, 7, 0.1) 100%);
        border-left: 4px solid #ffc107;
        padding: 0.75rem 1rem;
        border-radius: 8px;
        margin-bottom: 0.5rem;
    }
    
    .weakness-low {
        background: linear-gradient(135deg, rgba(40, 167, 69, 0.3) 0%, rgba(40, 167, 69, 0.1) 100%);
        border-left: 4px solid #28a745;
        padding: 0.75rem 1rem;
        border-radius: 8px;
        margin-bottom: 0.5rem;
    }
    
    /* Logo animation */
    @keyframes pulse {
        0% { opacity: 1; }
        50% { opacity: 0.7; }
        100% { opacity: 1; }
    }
    
    .logo-container {
        text-align: center;
        padding: 1rem;
        animation: pulse 2s infinite;
    }
    
    /* Divider */
    hr {
        border: none;
        height: 1px;
        background: linear-gradient(90deg, transparent 0%, rgba(255, 70, 85, 0.3) 50%, transparent 100%);
        margin: 1.5rem 0;
    }
    
    /* Data source info box */
    .data-source {
        background: linear-gradient(135deg, rgba(0, 123, 255, 0.1) 0%, rgba(0, 123, 255, 0.05) 100%);
        border-left: 4px solid #007bff;
        padding: 1rem;
        border-radius: 8px;
        margin-bottom: 1rem;
        color: #ccc;
    }
    
    /* DataFrame enhancements */
    [data-testid="stDataFrame"] > div {
        border-radius: 10px;
        overflow: hidden;
    }
    
    [data-testid="stDataFrame"] table {
        border-collapse: separate;
        border-spacing: 0;
    }
    
    /* Section headers */
    .stMarkdown h4 {
        color: #e0e0e0 !important;
        border-bottom: 2px solid rgba(255, 70, 85, 0.3);
        padding-bottom: 0.5rem;
        margin-top: 1.5rem;
    }
    
    /* Spinner */
    .stSpinner > div {
        border-top-color: #ff4655 !important;
    }
    
    /* Welcome page animations */
    @keyframes fadeInUp {
        from {
            opacity: 0;
            transform: translateY(20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }
    
    .stats-card {
        animation: fadeInUp 0.5s ease-out;
    }
    
    /* Quick action buttons glow on sidebar */
    [data-testid="stSidebar"] .stButton > button:hover {
        box-shadow: 0 0 25px rgba(255, 70, 85, 0.4);
    }
</style>
""", unsafe_allow_html=True)

# ============== SESSION STATE ==============
if 'analyzer' not in st.session_state:
    st.session_state.analyzer = GeminiAnalyzer(api_key=GEMINI_API_KEY)
if 'conversation' not in st.session_state:
    st.session_state.conversation = ConversationManager()
if 'scouting_data' not in st.session_state:
    st.session_state.scouting_data = None
if 'selected_team' not in st.session_state:
    st.session_state.selected_team = None
if 'report_generated' not in st.session_state:
    st.session_state.report_generated = False
if 'messages' not in st.session_state:
    st.session_state.messages = []
if 'dynamic_engine' not in st.session_state:
    st.session_state.dynamic_engine = DynamicScoutingEngine()
    st.session_state.dynamic_engine.connect()


def load_team_data(team_name: str, num_matches: int) -> dict:
    """Load scouting data for a team from the database."""
    with ScoutingEngine() as engine:
        return engine.generate_full_scouting_data(team_name, num_matches)


def get_teams() -> list:
    """Get all available teams."""
    with ScoutingEngine() as engine:
        return engine.get_all_teams()


def ask_dynamic_question(question: str, team_name: str) -> dict:
    """Use dynamic SQL generation to answer a question."""
    return st.session_state.dynamic_engine.ask(question, team_name)


def display_chat_message(role: str, content: str, timestamp: str = None):
    """Display a chat message."""
    if role == "user":
        st.markdown(f"""
        <div class="chat-message user-message">
            <strong>🙋 Coach</strong> {f'<span style="color:#666;font-size:0.8rem;">({timestamp})</span>' if timestamp else ''}
            <br>{content}
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div class="chat-message assistant-message">
            <strong>🤖 Analyst</strong> {f'<span style="color:#666;font-size:0.8rem;">({timestamp})</span>' if timestamp else ''}
        </div>
        """, unsafe_allow_html=True)
        st.markdown(content)


def main():
    # ============== SIDEBAR ==============
    with st.sidebar:
        # Logo and branding
        st.markdown("""
        <div class="logo-container">
            <h1 style="font-size: 2.5rem; margin: 0;">🎮</h1>
            <h2 style="background: linear-gradient(135deg, #ff4655 0%, #ffa500 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin: 0;">C9 SCOUTING</h2>
            <p style="color: #666; font-size: 0.8rem; margin-top: 0.5rem;">VALORANT Analytics Platform</p>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("---")
        
        # API Status with nice badge
        if st.session_state.analyzer.is_configured():
            st.markdown("""
            <div style="background: linear-gradient(135deg, rgba(40, 167, 69, 0.2) 0%, rgba(40, 167, 69, 0.1) 100%); 
                        border: 1px solid #28a745; border-radius: 8px; padding: 0.75rem; text-align: center;">
                <span style="color: #28a745;">⚡ Gemini AI Connected</span>
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown("""
            <div style="background: linear-gradient(135deg, rgba(255, 70, 85, 0.2) 0%, rgba(255, 70, 85, 0.1) 100%); 
                        border: 1px solid #ff4655; border-radius: 8px; padding: 0.75rem; text-align: center;">
                <span style="color: #ff4655;">❌ Gemini Not Connected</span>
            </div>
            """, unsafe_allow_html=True)
            st.info("Add GEMINI_API_KEY to .env file")
        
        st.markdown("---")
        
        # Team Selection
        st.markdown("### 🎯 Select Opponent")
        
        try:
            teams = get_teams()
            selected_team = st.selectbox(
                "Team to Scout:",
                options=teams,
                index=teams.index("Sentinels") if "Sentinels" in teams else 0
            )
            
            num_matches = st.slider(
                "Matches to Analyze:",
                min_value=5,
                max_value=20,
                value=10
            )
            
            if st.button("🔍 Load Team Data", type="primary"):
                with st.spinner(f"Loading {selected_team} data..."):
                    # Load data from database
                    st.session_state.scouting_data = load_team_data(selected_team, num_matches)
                    st.session_state.selected_team = selected_team
                    st.session_state.report_generated = False
                    st.session_state.messages = []
                    
                    # Initialize Gemini with team context
                    if st.session_state.analyzer.is_configured():
                        init_response = st.session_state.analyzer.set_team_context(
                            selected_team, 
                            st.session_state.scouting_data
                        )
                        st.session_state.messages.append({
                            "role": "assistant",
                            "content": f"✅ **Team data loaded for {selected_team}**\n\n{init_response}\n\n**What would you like to know?** You can:\n- Ask me to generate a full scouting report\n- Ask specific questions about maps, players, compositions\n- Request tactical analysis or counter-strategies",
                            "time": datetime.now().strftime("%H:%M")
                        })
                    else:
                        st.session_state.messages.append({
                            "role": "assistant", 
                            "content": f"✅ **Team data loaded for {selected_team}**\n\n⚠️ Gemini not configured - showing raw data only.",
                            "time": datetime.now().strftime("%H:%M")
                        })
                    
                st.rerun()
                
        except Exception as e:
            st.error(f"Database error: {e}")
        
        st.markdown("---")
        
        # Quick Actions
        if st.session_state.scouting_data:
            st.markdown("### ⚡ Quick Analysis")
            
            if st.button("📋 Full Scouting Report"):
                st.session_state.pending_action = "full_report"
                st.rerun()
            
            if st.button("🗺️ Map Veto Strategy"):
                st.session_state.pending_action = "map_veto"
                st.rerun()
            
            if st.button("👤 Player Targeting"):
                st.session_state.pending_action = "player_targeting"
                st.rerun()
            
            if st.button("🎯 Pistol Strategy"):
                st.session_state.pending_action = "pistol_strategy"
                st.rerun()
            
            if st.button("⚠️ Weakness Deep Dive"):
                st.session_state.pending_action = "weakness_deep_dive"
                st.rerun()
            
            st.markdown("---")
            
            if st.button("🗑️ Clear Chat"):
                st.session_state.messages = []
                st.rerun()
    
    # ============== MAIN CONTENT ==============
    
    # Header with team info
    if st.session_state.selected_team:
        col1, col2, col3, col4 = st.columns([3, 1, 1, 1])
        with col1:
            st.markdown(f"""
            <h1 class='main-header'>🎯 Scouting: {st.session_state.selected_team}</h1>
            <p style='color: #888; margin-top: -10px;'>AI-powered opponent analysis • Data from GRID Esports</p>
            """, unsafe_allow_html=True)
        
        if st.session_state.scouting_data:
            overview = st.session_state.scouting_data.get('overview', {})
            pistol = st.session_state.scouting_data.get('pistol_rounds', {})
            
            with col2:
                st.metric("📊 Record", overview.get('series_record', 'N/A'), f"{overview.get('win_rate', 0)}% WR")
            with col3:
                st.metric("🎯 Pistol WR", f"{pistol.get('overall_pistol_win_rate', 0)}%")
            with col4:
                map_stats = overview.get('map_stats', [])
                if map_stats:
                    best_map = max(map_stats, key=lambda x: x['win_rate'])
                    st.metric("🗺️ Best Map", best_map['map'].title(), f"{best_map['win_rate']}%")
    else:
        st.markdown("<h1 class='main-header'>🎮 VALORANT Scouting Tool</h1>", unsafe_allow_html=True)
        
        # Welcome card
        st.markdown("""
        <div class="stats-card">
            <h4>👋 Welcome, Coach!</h4>
            <p style="color: #ccc;">Select a team from the sidebar to begin scouting. This tool provides:</p>
            <ul style="color: #aaa;">
                <li>📊 <strong>Data-driven analysis</strong> from 196 series & 6,878 rounds</li>
                <li>🤖 <strong>AI-powered insights</strong> using Llama 3.3 70B</li>
                <li>💬 <strong>Interactive Q&A</strong> for detailed questions</li>
                <li>⚠️ <strong>Weakness detection</strong> with counter-strategies</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
    
    # Tabs: Chat and Raw Data
    if st.session_state.scouting_data:
        tab_chat, tab_data = st.tabs(["💬 Analysis Chat", "📊 Raw Data"])
        
        with tab_chat:
            # Chat container
            chat_container = st.container()
            
            # Handle pending actions
            if hasattr(st.session_state, 'pending_action'):
                action = st.session_state.pending_action
                del st.session_state.pending_action
                
                action_prompts = {
                    "full_report": "Generate a comprehensive scouting report",
                    "map_veto": "Analyze map veto strategy",
                    "player_targeting": "Analyze player targeting strategy",
                    "pistol_strategy": "Deep dive into pistol round strategy",
                    "weakness_deep_dive": "Provide exhaustive weakness analysis"
                }
                
                prompt = action_prompts.get(action, "Generate analysis")
                
                # Add user message
                st.session_state.messages.append({
                    "role": "user",
                    "content": prompt,
                    "time": datetime.now().strftime("%H:%M")
                })
                
                # Generate response
                with st.spinner("Analyzing..."):
                    if action == "full_report":
                        response = st.session_state.analyzer.generate_full_report()
                    else:
                        response = st.session_state.analyzer.get_specific_analysis(action)
                    
                    st.session_state.messages.append({
                        "role": "assistant",
                        "content": response,
                        "time": datetime.now().strftime("%H:%M")
                    })
                
                st.rerun()
            
            # Display chat messages
            with chat_container:
                for msg in st.session_state.messages:
                    if msg["role"] == "user":
                        with st.chat_message("user"):
                            st.markdown(msg["content"])
                    else:
                        with st.chat_message("assistant"):
                            st.markdown(msg["content"])
            
            # Chat input
            if prompt := st.chat_input("Ask about the team (e.g., 'What's their worst map?' or 'How do I beat them on Lotus?')"):
                # Add user message
                st.session_state.messages.append({
                    "role": "user",
                    "content": prompt,
                    "time": datetime.now().strftime("%H:%M")
                })
                
                # Display user message immediately
                with st.chat_message("user"):
                    st.markdown(prompt)
                
                # Generate and display assistant response using DYNAMIC SQL
                with st.chat_message("assistant"):
                    with st.spinner("🔍 Generating query & analyzing..."):
                        # Use dynamic SQL generation
                        dynamic_result = ask_dynamic_question(prompt, st.session_state.selected_team)
                        
                        if dynamic_result.get('error'):
                            # Fallback to static analyzer if dynamic fails
                            response = st.session_state.analyzer.ask_question(prompt)
                        elif dynamic_result.get('interpretation'):
                            # Build response with SQL info + interpretation
                            response = dynamic_result['interpretation']
                            
                            # Optionally show the SQL query in an expander
                            if dynamic_result.get('sql'):
                                response += f"\n\n<details><summary>📊 View Generated SQL</summary>\n\n```sql\n{dynamic_result['sql']}\n```\n</details>"
                        else:
                            # Fallback to static analyzer
                            response = st.session_state.analyzer.ask_question(prompt)
                        
                        st.markdown(response, unsafe_allow_html=True)
                
                # Add to history
                st.session_state.messages.append({
                    "role": "assistant",
                    "content": response,
                    "time": datetime.now().strftime("%H:%M")
                })
        
        with tab_data:
            st.markdown("""
            <div class="stats-card" style="margin-bottom: 1.5rem;">
                <h3 style="color: #ff4655; margin: 0 0 0.5rem 0;">📊 Raw Scouting Data</h3>
                <p style="color: #888; margin: 0; font-size: 0.9rem;">
                    ℹ️ Ground truth data from the database. All AI analysis is grounded in this data.
                </p>
            </div>
            """, unsafe_allow_html=True)
            
            data = st.session_state.scouting_data
            
            # Overview Section
            st.markdown("#### 📈 Team Overview")
            overview = data.get('overview', {})
            col1, col2, col3, col4 = st.columns(4)
            with col1:
                st.metric("📊 Series Record", overview.get('series_record', 'N/A'))
            with col2:
                st.metric("🏆 Win Rate", f"{overview.get('win_rate', 0)}%")
            with col3:
                pistol = data.get('pistol_rounds', {})
                st.metric("🎯 Pistol WR", f"{pistol.get('overall_pistol_win_rate', 0)}%")
            with col4:
                st.metric("🎮 Total Rounds", overview.get('total_rounds', 'N/A'))
            
            st.markdown("<br>", unsafe_allow_html=True)
            
            # Map Stats with visual enhancements
            st.markdown("#### 🗺️ Map Performance")
            map_stats = overview.get('map_stats', [])
            if map_stats:
                df = pd.DataFrame(map_stats)
                df['map'] = df['map'].str.title()
                df = df.rename(columns={
                    'map': '🗺️ Map',
                    'wins': '✅ Wins', 
                    'losses': '❌ Losses',
                    'win_rate': '📊 Win Rate %',
                    'rounds_played': '🎮 Rounds'
                })
                st.dataframe(df, use_container_width=True, hide_index=True)
            
            st.markdown("<br>", unsafe_allow_html=True)
            
            # Players with enhanced display
            st.markdown("#### 👥 Player Statistics")
            players = data.get('players', {}).get('players', [])
            if players:
                df = pd.DataFrame([{
                    '👤 Player': p['name'],
                    '🎮 Games': p['games'],
                    '⚔️ K/D': p['kd_ratio'],
                    '📊 KDA': p['kda'],
                    '🎯 Kills': p['kills'],
                    '💀 Deaths': p['deaths']
                } for p in players])
                st.dataframe(df, use_container_width=True, hide_index=True)
            
            st.markdown("<br>", unsafe_allow_html=True)
            
            # Weaknesses with styled cards
            st.markdown("#### ⚠️ Identified Weaknesses")
            weaknesses = data.get('weaknesses', {}).get('weaknesses', [])
            if weaknesses:
                for w in weaknesses:
                    severity = w['severity']
                    css_class = f"weakness-{severity.lower()}"
                    icon = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(severity, "⚪")
                    st.markdown(f"""
                    <div class="{css_class}">
                        <strong>{icon} {w['category']}</strong><br>
                        <span style="color: #ccc;">{w['finding']}</span>
                    </div>
                    """, unsafe_allow_html=True)
            else:
                st.info("No significant weaknesses identified")
            
            st.markdown("<br>", unsafe_allow_html=True)
            
            # Full JSON in expander
            with st.expander("📄 View Complete JSON Data"):
                st.json(data)
    
    else:
        # Welcome screen with beautiful cards
        st.markdown("""
        <div style="text-align: center; padding: 2rem 0;">
            <h1 style="font-size: 3rem; margin-bottom: 0.5rem;">🎮</h1>
            <h2 style="background: linear-gradient(135deg, #ff4655 0%, #ff6b6b 50%, #ffa500 100%); 
                       -webkit-background-clip: text; -webkit-text-fill-color: transparent;
                       font-size: 2.5rem; margin-bottom: 0.5rem;">
                Welcome, Coach!
            </h2>
            <p style="color: #888; font-size: 1.1rem;">Your AI-powered VALORANT opponent analysis platform</p>
        </div>
        """, unsafe_allow_html=True)
        
        # Feature cards in columns
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("""
            <div class="stats-card">
                <h4>📊 Data-Driven Analysis</h4>
                <p style="color: #ccc;">Access insights from <strong style="color: #ff4655;">196 series</strong> 
                and <strong style="color: #ff4655;">6,878 rounds</strong> of professional VALORANT data.</p>
            </div>
            """, unsafe_allow_html=True)
            
            st.markdown("""
            <div class="stats-card">
                <h4>💬 Interactive Q&A</h4>
                <p style="color: #ccc;">Ask detailed questions about any opponent - strategies, 
                player tendencies, map preferences, and more.</p>
            </div>
            """, unsafe_allow_html=True)
        
        with col2:
            st.markdown("""
            <div class="stats-card">
                <h4>🤖 AI-Powered Insights</h4>
                <p style="color: #ccc;">Powered by <strong style="color: #ff4655;">Llama 3.3 70B</strong> 
                for intelligent analysis grounded in real match data.</p>
            </div>
            """, unsafe_allow_html=True)
            
            st.markdown("""
            <div class="stats-card">
                <h4>⚠️ Weakness Detection</h4>
                <p style="color: #ccc;">Automatically identifies opponent vulnerabilities with 
                actionable counter-strategies.</p>
            </div>
            """, unsafe_allow_html=True)
        
        # How it works section
        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("""
        <div class="stats-card" style="text-align: center;">
            <h4 style="margin-bottom: 1.5rem;">🔄 How It Works</h4>
            <div style="display: flex; justify-content: center; align-items: center; flex-wrap: wrap; gap: 1rem;">
                <div style="background: rgba(255, 70, 85, 0.1); border-radius: 12px; padding: 1rem 1.5rem;">
                    <p style="font-size: 1.5rem; margin: 0;">🗄️</p>
                    <p style="color: #ff4655; font-weight: 600; margin: 0.5rem 0 0 0;">DuckDB</p>
                    <p style="color: #888; font-size: 0.8rem; margin: 0;">Ground Truth</p>
                </div>
                <p style="color: #ff4655; font-size: 1.5rem;">→</p>
                <div style="background: rgba(255, 70, 85, 0.1); border-radius: 12px; padding: 1rem 1.5rem;">
                    <p style="font-size: 1.5rem; margin: 0;">📊</p>
                    <p style="color: #ff4655; font-weight: 600; margin: 0.5rem 0 0 0;">Raw Data</p>
                    <p style="color: #888; font-size: 0.8rem; margin: 0;">JSON Export</p>
                </div>
                <p style="color: #ff4655; font-size: 1.5rem;">→</p>
                <div style="background: rgba(255, 70, 85, 0.1); border-radius: 12px; padding: 1rem 1.5rem;">
                    <p style="font-size: 1.5rem; margin: 0;">🤖</p>
                    <p style="color: #ff4655; font-weight: 600; margin: 0.5rem 0 0 0;">Llama AI</p>
                    <p style="color: #888; font-size: 0.8rem; margin: 0;">Analysis</p>
                </div>
            </div>
            <p style="color: #666; font-size: 0.9rem; margin-top: 1.5rem;">
                ✅ All statistics come from the database • ✅ AI only analyzes real data • ✅ Raw data always visible
            </p>
        </div>
        """, unsafe_allow_html=True)
        
        # Get started call to action
        st.markdown("""
        <div style="text-align: center; padding: 2rem 0;">
            <p style="color: #888; font-size: 1.1rem;">👈 <strong>Select a team from the sidebar</strong> to begin scouting!</p>
        </div>
        """, unsafe_allow_html=True)


if __name__ == "__main__":
    main()
